---
kind: pipeline
type: docker
name: Trufflehog
    
steps:
- name : Truffle-hog clone  
  image: docker:git
  commands:    
     - git clone https://github.com/moengage/moe-truffleHog.git --branch dev
  when:
    event:
    - push
    
- name: Run truffle-hog
  image: python:2.7-alpine
  commands:
   when:
    event:
    - push
  
