pipeline:
  deps:
    image: docker:git
    commands:
     - git clone https://github.com/moengage/moe-truffleHog.git || true
  build:
    image: python:3.5.1-alpine
    commands:
      - apk add --no-cache git
      - cd moe-truffleHog
      -	pip install -r requirements.txt
      -	pip list
      -	ls -la
      - git status
      -	python truffleHog/truffleHog.py  --max_depth 1 --regex --branch master https://github.com/ParasJain-dev/Alice-Test-App.git --entropy true > output.txt
      - cat output.txt
      - flag='False'
      - if [ -s output.txt ]; then flag='True'; fi
      - if [ "$flag" = 'True' ]; then echo "Tokens found" cat output.txt ;else echo "No Tokens Found"; fi
