---
kind: pipeline
type: docker
name: Trufflehog
    
steps:
- name : Truffle-hog clone  
  image: docker:git
  commands:    
     - git clone https://github.com/moengage/moe-truffleHog.git --branch dev
  when:
    event:
    - pull_request
    
- name: Run truffle-hog
  image: python:2.7-alpine
  commands:
      - apk add --no-cache git
      - echo $DRONE_SOURCE_BRANCH
      - echo $DRONE_REPO
      - cd moe-truffleHog
 
