SLACK_USER_LIST = "https://slack.com/api/users.list?token="
GITHUB_USERS = "https://api.github.com/users/"
GITHUB_MEMBERS_LIST = "https://api.github.com/orgs/{org}/members?page="
GITHUB_MEMBERS = "https://api.github.com/orgs/{org}/members"
GITHUB_REPO_MEMBER = "https://api.github.com/repos/{org}/{repo}"
THUMBS_UP_ICON = "\ud83d\udc4d"
GITHUB_REVIEW_ACCEPT_KEY = "application/vnd.github.black-cat-preview+json"
EP_REVIEWS = "reviews"
EP_COMMENTS = "comments"
STATE_OPEN = "open"
STATE_CLOSED = "closed"
SLACK_ICON = "https://cloud.githubusercontent.com/assets/12966925/25132384/021095fc-2467-11e7-95c0-78917bf4d52a.png"
bot_name = "alice"


