SLACK_USER_LIST = "https://slack.com/api/users.list?token="
GITHUB_USER_LIST = "https://api.github.com/orgs/{org}/members?page="
THUMBS_UP_ICON = "\ud83d\udc4d"
GITHUB_REVIEW_ACCEPT_KEY = "application/vnd.github.black-cat-preview+json"
EP_REVIEWS = "reviews"
EP_COMMENTS = "comments"
STATE_OPEN = "open"
STATE_CLOSED = "closed"
